android {
    namespace 'com.lulux.detector'
    compileSdk 28  // turun dari 35, cukup untuk Android 9
    
    defaultConfig {
        applicationId 'com.lulux.detector'
        minSdk 28      // Android 9 (API 28)
        targetSdk 28   // target Android 9
        versionCode 1
        versionName '1.0'
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
}
